---
- name: Deploying LAMP stack
  hosts: nodes
  remote_user: ansadmin
  become: yes

  tasks:
    - package: "name=httpd state=present"
    - copy: "src=index.html dest=/var/www/html"
    - service: "name=httpd state=started enabled=true"
