---
- name: Install Podman
  hosts: nodes
  become: true
  tasks:
    - name: update ec2 instance
      dnf:
        name: "*"
        state: latest
        update_cache: yes
    
    - name: Execute dnf command
      command: dnf module list | grep container-tools
      register: module_output

    - name: Display module output
      debug:
        var: module_output.stdout_lines

    - name: Enable container-tools module
      shell: sudo dnf module enable -y container-tools:rhel8
        
    - name: Install required packages
      package:
        name:
#          - container-tools:rhel8
          - podman
          - slirp4netns
          - skopeo
          - buildah
        state: present
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

    - name: Log error message for unsupported platform
      debug:
        msg: "No valid platform. Exiting"
      when: ansible_distribution != 'RedHat'

    - name: Start and enable Podman service
      service:
        name: podman
        state: started
        enabled: true


