---

- name: Installing Apache server
  yum: name=httpd state=latest
  tags:
  - installapache

- name: Start Apache Server service
  service: name=httpd state=started
  tags:
  - startapache

- name: Copy Index PHP file
  copy: src=index.html dest=/var/www/html/
  notify:
  - restartweb
